package com.ragl.divide.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFC10067)
val onPrimaryLight = Color(0xFFffffff)
val primaryContainerLight = Color(0xFFFFF1F7)
val onPrimaryContainerLight = Color(0xFF000000)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF191919)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF191919)

val primaryDark = Color(0xFFE42E81)
val onPrimaryDark = Color(0xFFffffff)
val primaryContainerDark = Color(0xFF202531)
val onPrimaryContainerDark = Color(0xFFffffff)
val backgroundDark = Color(0xFF141922)
val onBackgroundDark = Color(0xCBFFFFFF)
val surfaceDark = Color(0xFF141922)
val onSurfaceDark = Color(0xCBFFFFFF)

//val primaryLight = Color(0xFF2AC100)
//val onPrimaryLight = Color(0xFFffffff)
//val primaryContainerLight = Color(0xFFE9FFE3)
//val onPrimaryContainerLight = Color(0xFF000000)
//val backgroundLight = Color(0xFFFFFFFF)
//val onBackgroundLight = Color(0xFF191919)
//val surfaceLight = Color(0xFFFFFFFF)
//val onSurfaceLight = Color(0xFF191919)
//
//val primaryDark = Color(0xFF3EB822)
//val onPrimaryDark = Color(0xFFffffff)
//val primaryContainerDark = Color(0xFF202531)
//val onPrimaryContainerDark = Color(0xFFffffff)
//val backgroundDark = Color(0xFF141922)
//val onBackgroundDark = Color(0xCBFFFFFF)
//val surfaceDark = Color(0xFF141922)
//val onSurfaceDark = Color(0xCBFFFFFF)

//val primaryLight = Color(0xFF8E4956)
//val onPrimaryLight = Color(0xFFFFFFFF)
//val primaryContainerLight = Color(0xFFFFD9DD)
//val onPrimaryContainerLight = Color(0xFF3B0715)
//val secondaryLight = Color(0xFF76565A)
//val onSecondaryLight = Color(0xFFFFFFFF)
//val secondaryContainerLight = Color(0xFFFFD9DD)
//val onSecondaryContainerLight = Color(0xFF2C1519)
//val tertiaryLight = Color(0xFF795831)
//val onTertiaryLight = Color(0xFFFFFFFF)
//val tertiaryContainerLight = Color(0xFFFFDDB9)
//val onTertiaryContainerLight = Color(0xFF2B1700)
//val errorLight = Color(0xFFBA1A1A)
//val onErrorLight = Color(0xFFFFFFFF)
//val errorContainerLight = Color(0xFFFFDAD6)
//val onErrorContainerLight = Color(0xFF410002)
//val backgroundLight = Color(0xFFFFF8F7)
//val onBackgroundLight = Color(0xFF22191A)
//val surfaceLight = Color(0xFFFFF8F7)
//val onSurfaceLight = Color(0xFF22191A)
//val surfaceVariantLight = Color(0xFFF3DDDF)
//val onSurfaceVariantLight = Color(0xFF524345)
//val outlineLight = Color(0xFF847375)
//val outlineVariantLight = Color(0xFFD6C2C3)
//val scrimLight = Color(0xFF000000)
//val inverseSurfaceLight = Color(0xFF382E2F)
//val inverseOnSurfaceLight = Color(0xFFFEEDEE)
//val inversePrimaryLight = Color(0xFFFFB2BD)
//
//val primaryDark = Color(0xFFFFB2BD)
//val onPrimaryDark = Color(0xFF561D29)
//val primaryContainerDark = Color(0xFF72333F)
//val onPrimaryContainerDark = Color(0xFFFFD9DD)
//val secondaryDark = Color(0xFFE5BDC1)
//val onSecondaryDark = Color(0xFF43292D)
//val secondaryContainerDark = Color(0xFF5C3F43)
//val onSecondaryContainerDark = Color(0xFFFFD9DD)
//val tertiaryDark = Color(0xFFEABF8F)
//val onTertiaryDark = Color(0xFF452B07)
//val tertiaryContainerDark = Color(0xFF5E411C)
//val onTertiaryContainerDark = Color(0xFFFFDDB9)
//val errorDark = Color(0xFFFFB4AB)
//val onErrorDark = Color(0xFF690005)
//val errorContainerDark = Color(0xFF93000A)
//val onErrorContainerDark = Color(0xFFFFDAD6)
//val backgroundDark = Color(0xFF191112)
//val onBackgroundDark = Color(0xFFF0DEE0)
//val surfaceDark = Color(0xFF191112)
//val onSurfaceDark = Color(0xFFF0DEE0)
//val surfaceVariantDark = Color(0xFF524345)
//val onSurfaceVariantDark = Color(0xFFD6C2C3)
//val outlineDark = Color(0xFF9F8C8E)
//val outlineVariantDark = Color(0xFF524345)
//val scrimDark = Color(0xFF000000)
//val inverseSurfaceDark = Color(0xFFF0DEE0)
//val inverseOnSurfaceDark = Color(0xFF382E2F)
//val inversePrimaryDark = Color(0xFF8E4956)


